name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: flmorg/universal-workflows/.github/workflows/dotnet.release.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
    secrets: inherit